// Cross-language fixture proof: this envelope was generated by real Python
// `pycryptodome` AES-256-GCM using the exact same KDF/salt/iterations as
// `forge/connectors/secrets.py`. If Rust's `decrypt()` can open this, the
// wire format is truly compatible — not just self-consistent within Rust.
use forge_crypto::connector_secrets::decrypt;

#[test]
fn decrypts_real_python_generated_envelope() {
    // Generated by: python -c "... pycryptodome AES.new(key, MODE_GCM, nonce=b'\x00'*12) ..."
    // key_material = "forge-canary-key-for-verify-cmd-xxxxxxxxxxx"
    // context = "forge.connector_secrets.v1:1001:shodan_host_lookup:FORGE_SHODAN_API_KEY"
    // plaintext = "canary-secret-value"
    let envelope = r#"{"alg":"AES-256-GCM","ciphertext":"relmQRB5DLwX4PuDiqQH-ob8CQ==","kdf":"PBKDF2-HMAC-SHA256:200000","nonce":"AAAAAAAAAAAAAAAA","tag":"g-8p5YefoNO96V8kzfuMYw==","v":1}"#;
    let key_material = "forge-canary-key-for-verify-cmd-xxxxxxxxxxx";
    let context = "forge.connector_secrets.v1:1001:shodan_host_lookup:FORGE_SHODAN_API_KEY";

    let recovered = decrypt(envelope, context, key_material)
        .expect("Rust must decrypt a real Python-generated envelope");
    assert_eq!(recovered, "canary-secret-value");
}
