"""Nemesis-compatible artifact handoff (Explore #13).

Exports sanitized engagement evidence from a FORGE engagement DB into a
JSON bundle that the operator can ingest into a Nemesis post-exploitation
evidence management instance.

Design invariants:
* Read-only — never writes to the engagement DB.
* Secret material is redacted (credential hashes replaced with ``<redacted>``).
* Scope-manifest paths are never included.
* Only public-facing, non-sensitive fields are exported.
* Output is valid Nemesis ingest format v1.

Nemesis ingest format:
    {
        "nemesis_schema_version": "1.0",
        "source": "FORGE",
        "engagement_id": <int>,
        "timestamp": "<ISO-8601>",
        "findings": [...],
        "files": [...],
        "credentials": [...],
        "paths": [...],
        "notes": "..."
    }

Usage:
    from forge.graph.nemesis_export import build_nemesis_bundle
    bundle = build_nemesis_bundle(engagement_id=1001, db_path=Path("1001.db"))
"""

from __future__ import annotations

import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

__all__ = ["build_nemesis_bundle"]

_MAX_ROWS = 500


def _safe_str(value: Any, max_len: int = 256) -> str:
    return str(value or "")[:max_len].strip()


def build_nemesis_bundle(
    *,
    engagement_id: int,
    db_path: Path,
    limit: int = _MAX_ROWS,
) -> dict[str, Any]:
    """Build a Nemesis-compatible JSON bundle from the engagement DB.

    Args:
        engagement_id: Engagement to export.
        db_path: Path to the engagement SQLite DB.
        limit: Max rows per section (default 500).

    Returns:
        Dict matching Nemesis ingest schema v1.  Call ``json.dumps(bundle)``
        to serialise.  The bundle contains sanitized findings, artifact
        paths, and metadata — no raw secrets.
    """
    bundle: dict[str, Any] = {
        "nemesis_schema_version": "1.0",
        "source": "FORGE",
        "engagement_id": engagement_id,
        "timestamp": datetime.now(tz=timezone.utc).isoformat(),
        "findings": [],
        "files": [],
        "credentials": [],
        "paths": [],
        "notes": (
            "Generated by FORGE operator toolkit. "
            "Credential hashes redacted. "
            "Import via: nemesis-cli ingest --file nemesis_bundle.json"
        ),
    }

    if not db_path.exists():
        bundle["error"] = f"Engagement DB not found: {db_path}"
        return bundle

    try:
        con = sqlite3.connect(str(db_path))
        con.row_factory = sqlite3.Row
    except Exception as exc:  # noqa: BLE001
        bundle["error"] = f"Cannot open DB: {exc}"
        return bundle

    try:
        # Findings
        try:
            rows = con.execute(
                "SELECT title, severity, category, domain, status, description "
                "FROM findings WHERE engagement_id = ? LIMIT ?",
                (engagement_id, limit),
            ).fetchall()
            bundle["findings"] = [
                {
                    "title": _safe_str(r["title"]),
                    "severity": _safe_str(r["severity"]),
                    "category": _safe_str(r["category"]),
                    "domain": _safe_str(r["domain"]),
                    "status": _safe_str(r["status"]),
                    "description": _safe_str(r.get("description") or "", 512),
                    "source": "FORGE",
                }
                for r in rows
            ]
        except sqlite3.OperationalError:
            pass

        # Artifact paths (sanitized — no local filesystem paths)
        try:
            rows = con.execute(
                "SELECT source_url, artifact_type, status "
                "FROM artifact_queue WHERE engagement_id = ? LIMIT ?",
                (engagement_id, limit),
            ).fetchall()
            bundle["files"] = [
                {
                    "source_url": _safe_str(r["source_url"]),
                    "artifact_type": _safe_str(r["artifact_type"]),
                    "status": _safe_str(r["status"]),
                }
                for r in rows
            ]
        except sqlite3.OperationalError:
            pass

        # Key findings (redacted hashes)
        try:
            rows = con.execute(
                "SELECT service, pattern, state, validation_status "
                "FROM key_scanner_findings WHERE engagement_id = ? LIMIT ?",
                (engagement_id, limit),
            ).fetchall()
            bundle["credentials"] = [
                {
                    "service": _safe_str(r["service"]),
                    "pattern": _safe_str(r["pattern"]),
                    "state": _safe_str(r["state"]),
                    "validation_status": _safe_str(r["validation_status"]),
                    "hash": "<redacted>",
                    "note": "Raw credential material redacted by FORGE export.",
                }
                for r in rows
            ]
        except sqlite3.OperationalError:
            pass

        # Seeds as path targets
        try:
            rows = con.execute(
                "SELECT seed_value, seed_type, created_at "
                "FROM seeds WHERE engagement_id = ? "
                "ORDER BY created_at DESC LIMIT ?",
                (engagement_id, limit),
            ).fetchall()
            bundle["paths"] = [
                {
                    "path": _safe_str(r["seed_value"]),
                    "type": _safe_str(r["seed_type"]),
                    "discovered_at": _safe_str(r["created_at"]),
                }
                for r in rows
            ]
        except sqlite3.OperationalError:
            pass

    finally:
        con.close()

    bundle["summary"] = {
        "findings": len(bundle["findings"]),
        "files": len(bundle["files"]),
        "credentials": len(bundle["credentials"]),
        "paths": len(bundle["paths"]),
    }

    return bundle
