#!/usr/bin/env sh
# FORGE cross-OS bootstrap (Linux / macOS)
#
# Idempotent. Safe to run any number of times.
#
# What it does:
#   1. Verifies Docker daemon is reachable
#   2. Creates .env.dev with strong random secrets if missing
#   3. Ensures secrets in .env.dev meet minimum length requirements
#   4. Prepares bind-mount directories (reports/, imports/, .forge_data/)
#   5. Optionally launches the dev stack
#
# Usage:
#   sh scripts/setup.sh          # setup only
#   sh scripts/setup.sh --up     # setup + docker compose up -d
#   sh scripts/setup.sh --force  # regenerate secrets in .env.dev

set -eu

UP=0
FORCE=0
for arg in "$@"; do
    case "$arg" in
        --up)    UP=1 ;;
        --force) FORCE=1 ;;
        -h|--help)
            grep '^#' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) printf 'unknown argument: %s\n' "$arg" >&2; exit 2 ;;
    esac
done

repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo"

step()  { printf '==> %s\n' "$1"; }
ok()    { printf '    OK  %s\n' "$1"; }
warn()  { printf '    !!  %s\n' "$1" >&2; }

new_secret() {
    # Args: byte length (double the hex-char length)
    n=${1:-32}
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$n"
    elif [ -r /dev/urandom ]; then
        # Portable fallback: xxd + head; strip newlines
        head -c "$n" /dev/urandom | od -An -tx1 | tr -d ' \n'
    else
        warn 'no openssl and /dev/urandom unavailable'
        return 1
    fi
}

# 1. Docker check
step 'Checking Docker daemon'
if ! docker info --format '{{.ServerVersion}}' >/dev/null 2>&1; then
    warn 'Docker daemon not reachable. Start Docker (Desktop / systemd), then re-run.'
    exit 1
fi
DVER=$(docker info --format '{{.ServerVersion}}')
ok "Docker $DVER reachable"

# 2. .env.dev
step 'Ensuring .env.dev exists with valid secrets'
ENV_FILE="$repo/.env.dev"
TMP_ENV=$(mktemp)
trap 'rm -f "$TMP_ENV"' EXIT

get_val() {
    key=$1
    [ -f "$ENV_FILE" ] || return 1
    grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2-
}

need_key() {
    key=$1
    val=$(get_val "$key" || true)
    if [ "$FORCE" = "1" ] || [ -z "${val:-}" ] || printf '%s' "$val" | grep -qE 'CHANGEME|PLACEHOLDER'; then
        return 0
    fi
    return 1
}

PG_PW=$(get_val FORGE_POSTGRES_PASSWORD || true)
WEB_KEY=$(get_val FORGE_WEB_SECRET_KEY || true)
BOOTSTRAP=$(get_val FORGE_WEB_BOOTSTRAP_TOKEN || true)
ENG_KEY=$(get_val FORGE_ENGAGEMENT_KEY || true)

if need_key FORGE_POSTGRES_PASSWORD;   then PG_PW=$(new_secret 16);  ok 'Generated FORGE_POSTGRES_PASSWORD';   else ok 'FORGE_POSTGRES_PASSWORD already set';   fi
if need_key FORGE_WEB_SECRET_KEY;      then WEB_KEY=$(new_secret 32); ok 'Generated FORGE_WEB_SECRET_KEY';      else ok 'FORGE_WEB_SECRET_KEY already set';      fi
if need_key FORGE_WEB_BOOTSTRAP_TOKEN; then BOOTSTRAP=$(new_secret 24); ok 'Generated FORGE_WEB_BOOTSTRAP_TOKEN'; else ok 'FORGE_WEB_BOOTSTRAP_TOKEN already set'; fi
if need_key FORGE_ENGAGEMENT_KEY;      then ENG_KEY=$(new_secret 32); ok 'Generated FORGE_ENGAGEMENT_KEY';      else ok 'FORGE_ENGAGEMENT_KEY already set';      fi

cat >"$TMP_ENV" <<EOF
# FORGE dev secrets — generated by scripts/setup.sh
# .gitignored — never commit

FORGE_POSTGRES_PASSWORD=$PG_PW
FORGE_WEB_SECRET_KEY=$WEB_KEY
FORGE_WEB_BOOTSTRAP_TOKEN=$BOOTSTRAP
FORGE_ENGAGEMENT_KEY=$ENG_KEY
FORGE_API_PORT=$(get_val FORGE_API_PORT || echo 8000)
FORGE_WEB_PORT=$(get_val FORGE_WEB_PORT || echo 8080)
FORGE_LLM_PROVIDER=$(get_val FORGE_LLM_PROVIDER || echo template)
FORGE_LOG_LEVEL=$(get_val FORGE_LOG_LEVEL || echo DEBUG)
FORGE_PUBLIC_BASE_URL=$(get_val FORGE_PUBLIC_BASE_URL || echo http://127.0.0.1:8080)
FORGE_TLS_TERMINATED_BY=$(get_val FORGE_TLS_TERMINATED_BY || echo none)
EOF

# Preserve any extra keys the user had in .env.dev that we don't manage
if [ -f "$ENV_FILE" ]; then
    while IFS= read -r line; do
        case "$line" in
            ''|\#*) continue ;;
            *=*)
                key=${line%%=*}
                case "$key" in
                    FORGE_POSTGRES_PASSWORD|FORGE_WEB_SECRET_KEY|FORGE_WEB_BOOTSTRAP_TOKEN|FORGE_ENGAGEMENT_KEY|FORGE_API_PORT|FORGE_WEB_PORT|FORGE_LLM_PROVIDER|FORGE_LOG_LEVEL|FORGE_PUBLIC_BASE_URL|FORGE_TLS_TERMINATED_BY)
                        ;;
                    *) printf '%s\n' "$line" >>"$TMP_ENV" ;;
                esac
                ;;
        esac
    done <"$ENV_FILE"
fi

mv "$TMP_ENV" "$ENV_FILE"
chmod 600 "$ENV_FILE" 2>/dev/null || true
trap - EXIT
ok '.env.dev written (mode 600)'

# 3. Bind-mount dirs
step 'Ensuring host bind-mount directories exist'
for d in reports imports .forge_data; do
    if [ ! -d "$repo/$d" ]; then
        mkdir -p "$repo/$d"
        ok "created $d/"
    else
        ok "$d/ exists"
    fi
done

# 4. Compose config sanity
step 'Validating docker/docker-compose.dev.yml'
if ! docker compose --env-file .env.dev -f docker/docker-compose.dev.yml config --quiet; then
    warn 'Compose config invalid'
    exit 1
fi
ok 'compose file valid'

# 5. Optional launch
if [ "$UP" = "1" ]; then
    step 'Bringing dev stack up'
    docker compose --env-file .env.dev -f docker/docker-compose.dev.yml up -d
    ok 'dev stack started'
    printf '\n'
    printf 'Next: sh dev.sh ps    # check health\n'
    printf '      sh dev.sh logs  # tail logs\n'
    printf '      http://127.0.0.1:8000/health\n'
    printf '      http://127.0.0.1:8080/health\n'
else
    printf '\n'
    printf 'Setup complete. Start with:  sh dev.sh\n'
fi
