# FORGE cross-OS bootstrap (Windows)
#
# Idempotent. Safe to run any number of times.
#
# What it does:
#   1. Verifies Docker Desktop is reachable
#   2. Creates .env.dev from .env.dev.example (or generates one) if missing
#   3. Ensures secrets in .env.dev meet minimum length requirements
#   4. Prepares bind-mount directories (reports/, imports/, .forge_data/)
#   5. Optionally launches the dev stack
#
# Usage:
#   pwsh -File scripts/setup.ps1           # setup only
#   pwsh -File scripts/setup.ps1 -Up       # setup + docker compose up -d
#   pwsh -File scripts/setup.ps1 -Force    # regenerate secrets in .env.dev

[CmdletBinding()]
param(
    [switch]$Up,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
Set-Location $repo

function Write-Step { param($msg) Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok   { param($msg) Write-Host "    OK  $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "    !!  $msg" -ForegroundColor Yellow }

function New-Secret {
    param([int]$Length = 48)
    # Cryptographically random hex; matches Python secrets.token_hex(N/2) length
    $bytes = [byte[]]::new([math]::Ceiling($Length / 2))
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return -join ($bytes | ForEach-Object { $_.ToString('x2') })
}

# 1. Docker check
Write-Step 'Checking Docker Desktop'
$v = docker info --format '{{.ServerVersion}}' 2>$null
if ($LASTEXITCODE -ne 0 -or -not $v) {
    Write-Warn 'Docker daemon not reachable. Start Docker Desktop, then re-run this script.'
    exit 1
}
Write-Ok "Docker $v reachable"

# 2. .env.dev
Write-Step 'Ensuring .env.dev exists with valid secrets'
$envFile = Join-Path $repo '.env.dev'
$needsWrite = $Force -or -not (Test-Path $envFile)
$existing = @{}
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$') {
            $existing[$Matches[1]] = $Matches[2]
        }
    }
}

$required = @{
    'FORGE_POSTGRES_PASSWORD'   = { New-Secret 32 }
    'FORGE_WEB_SECRET_KEY'      = { New-Secret 64 }
    'FORGE_WEB_BOOTSTRAP_TOKEN' = { New-Secret 48 }
    'FORGE_ENGAGEMENT_KEY'      = { New-Secret 64 }
}
foreach ($k in $required.Keys) {
    if ($Force -or -not $existing.ContainsKey($k) -or [string]::IsNullOrWhiteSpace($existing[$k]) -or $existing[$k] -match 'CHANGEME|PLACEHOLDER') {
        $existing[$k] = & $required[$k]
        $needsWrite = $true
        Write-Ok "Generated $k"
    } else {
        Write-Ok "$k already set"
    }
}
# Sensible dev defaults for optional keys
$defaults = @{
    'FORGE_API_PORT'         = '8000'
    'FORGE_WEB_PORT'         = '8080'
    'FORGE_LLM_PROVIDER'     = 'template'
    'FORGE_LOG_LEVEL'        = 'DEBUG'
    'FORGE_PUBLIC_BASE_URL'  = 'http://127.0.0.1:8080'
    'FORGE_TLS_TERMINATED_BY'= 'none'
}
foreach ($k in $defaults.Keys) {
    if (-not $existing.ContainsKey($k)) {
        $existing[$k] = $defaults[$k]
        $needsWrite = $true
    }
}

if ($needsWrite) {
    $ordered = @(
        'FORGE_POSTGRES_PASSWORD',
        'FORGE_WEB_SECRET_KEY',
        'FORGE_WEB_BOOTSTRAP_TOKEN',
        'FORGE_ENGAGEMENT_KEY',
        'FORGE_API_PORT',
        'FORGE_WEB_PORT',
        'FORGE_LLM_PROVIDER',
        'FORGE_LOG_LEVEL',
        'FORGE_PUBLIC_BASE_URL',
        'FORGE_TLS_TERMINATED_BY'
    )
    $extra = $existing.Keys | Where-Object { $ordered -notcontains $_ }
    $lines = @('# FORGE dev secrets — generated by scripts/setup.ps1', '# .gitignored — never commit', '')
    foreach ($k in ($ordered + $extra)) {
        if ($existing.ContainsKey($k)) { $lines += "$k=$($existing[$k])" }
    }
    Set-Content -Path $envFile -Value $lines -Encoding utf8
    Write-Ok '.env.dev written'
} else {
    Write-Ok '.env.dev already valid'
}

# 3. Bind-mount dirs
Write-Step 'Ensuring host bind-mount directories exist'
foreach ($d in @('reports', 'imports', '.forge_data')) {
    $p = Join-Path $repo $d
    if (-not (Test-Path $p)) {
        New-Item -ItemType Directory -Path $p -Force | Out-Null
        Write-Ok "created $d/"
    } else {
        Write-Ok "$d/ exists"
    }
}

# 4. Compose config sanity
Write-Step 'Validating docker/docker-compose.dev.yml'
docker compose --env-file .env.dev -f docker/docker-compose.dev.yml config --quiet
if ($LASTEXITCODE -ne 0) { Write-Warn 'Compose config invalid'; exit 1 }
Write-Ok 'compose file valid'

# 5. Optional launch
if ($Up) {
    Write-Step 'Bringing dev stack up'
    docker compose --env-file .env.dev -f docker/docker-compose.dev.yml up -d
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Write-Ok 'dev stack started'
    Write-Host ''
    Write-Host 'Next: pwsh -File dev.ps1 ps    # check health'
    Write-Host '      pwsh -File dev.ps1 logs  # tail logs'
    Write-Host '      http://127.0.0.1:8000/health'
    Write-Host '      http://127.0.0.1:8080/health'
} else {
    Write-Host ''
    Write-Host 'Setup complete. Start with:  pwsh -File dev.ps1'
}
