"""Tests for forge.collection.cloud.azure_credentials.

Every test hashes any secret material and asserts that raw values never appear
in the returned dataclass. The IMDS probe is guarded by a fake urlopen so no
real network traffic is generated by the test suite.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from unittest.mock import patch

import pytest

from forge.collection.cloud.azure_credentials import (
    AzureCredential,
    _HASH_PREFIX,
    _sha256,
    harvest_azure_credentials,
)


# --------------------------------------------------------------------------- #
# Hash helper                                                                 #
# --------------------------------------------------------------------------- #

class TestSha256:
    def test_hashes_str_with_prefix(self) -> None:
        expected = _HASH_PREFIX + hashlib.sha256(b"secret").hexdigest()
        assert _sha256("secret") == expected

    def test_hashes_bytes_with_prefix(self) -> None:
        expected = _HASH_PREFIX + hashlib.sha256(b"payload").hexdigest()
        assert _sha256(b"payload") == expected

    def test_none_returns_none(self) -> None:
        assert _sha256(None) is None

    def test_empty_returns_none(self) -> None:
        assert _sha256("") is None
        assert _sha256(b"") is None


# --------------------------------------------------------------------------- #
# Source 1: environment variables                                             #
# --------------------------------------------------------------------------- #

class TestHarvestEnv:
    def test_service_principal_env_hashed(self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
        monkeypatch.setenv("AZURE_TENANT_ID", "tenant-guid")
        monkeypatch.setenv("AZURE_CLIENT_ID", "client-guid")
        monkeypatch.setenv("AZURE_CLIENT_SECRET", "super-secret")
        monkeypatch.delenv("AZURE_STORAGE_CONNECTION_STRING", raising=False)

        creds = harvest_azure_credentials(azure_dir=tmp_path / "empty", include_imds=False)

        sp = [c for c in creds if c.type == "service_principal"]
        assert len(sp) == 1
        row = sp[0]
        assert row.tenant_id == "tenant-guid"
        assert row.client_id == "client-guid"
        assert row.secret_hash == _sha256("super-secret")
        # Raw secret must never leak.
        assert row.secret_hash != "super-secret"
        assert "super-secret" not in json.dumps(row.to_dict())

    def test_storage_connection_string_extracts_account_and_hashes_key(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        cs = (
            "DefaultEndpointsProtocol=https;"
            "AccountName=acmedata;"
            "AccountKey=SGVsbG9Xb3JsZEtleU1hdGVyaWFsMTIzNDU2Nzg5MEFCQ0RFRkc=;"
            "EndpointSuffix=core.windows.net"
        )
        monkeypatch.setenv("AZURE_STORAGE_CONNECTION_STRING", cs)
        monkeypatch.delenv("AZURE_CLIENT_ID", raising=False)
        monkeypatch.delenv("AZURE_CLIENT_SECRET", raising=False)
        monkeypatch.delenv("AZURE_TENANT_ID", raising=False)

        creds = harvest_azure_credentials(azure_dir=tmp_path / "empty", include_imds=False)

        storage = [c for c in creds if c.type == "storage_shared_key"]
        assert len(storage) == 1
        row = storage[0]
        assert row.account_name == "acmedata"
        assert row.secret_hash == _sha256("SGVsbG9Xb3JsZEtleU1hdGVyaWFsMTIzNDU2Nzg5MEFCQ0RFRkc=")
        assert "SGVsbG9Xb3JsZEtleU1hdGVyaWFsMTIzNDU2Nzg5MEFCQ0RFRkc=" not in json.dumps(row.to_dict())

    def test_missing_env_produces_nothing(self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
        for name in (
            "AZURE_TENANT_ID",
            "AZURE_CLIENT_ID",
            "AZURE_CLIENT_SECRET",
            "AZURE_STORAGE_CONNECTION_STRING",
        ):
            monkeypatch.delenv(name, raising=False)

        creds = harvest_azure_credentials(azure_dir=tmp_path / "empty", include_imds=False)

        assert creds == []


# --------------------------------------------------------------------------- #
# Source 2: azureProfile.json                                                 #
# --------------------------------------------------------------------------- #

class TestHarvestAzureProfile:
    def test_parses_subscriptions(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        for name in (
            "AZURE_TENANT_ID",
            "AZURE_CLIENT_ID",
            "AZURE_CLIENT_SECRET",
            "AZURE_STORAGE_CONNECTION_STRING",
        ):
            monkeypatch.delenv(name, raising=False)
        azure_dir = tmp_path / ".azure"
        azure_dir.mkdir()
        profile = {
            "subscriptions": [
                {
                    "id": "sub-guid-1",
                    "name": "Prod",
                    "state": "Enabled",
                    "tenantId": "tenant-1",
                    "environmentName": "AzureCloud",
                    "user": {"name": "ops@acme.example", "type": "user"},
                },
                {
                    "id": "sub-guid-2",
                    "name": "Dev",
                    "tenantId": "tenant-2",
                    "user": {"name": "sp:client-guid", "type": "servicePrincipal"},
                },
            ]
        }
        (azure_dir / "azureProfile.json").write_text(json.dumps(profile), encoding="utf-8-sig")

        creds = harvest_azure_credentials(azure_dir=azure_dir, include_imds=False)

        subs = [c for c in creds if c.type == "subscription_context"]
        assert {c.subscription_id for c in subs} == {"sub-guid-1", "sub-guid-2"}
        prod = next(c for c in subs if c.subscription_id == "sub-guid-1")
        assert prod.tenant_id == "tenant-1"
        assert prod.extra.get("name") == "Prod"
        assert prod.extra.get("user_type") == "user"

    def test_malformed_json_ignored(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        for name in ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_STORAGE_CONNECTION_STRING"):
            monkeypatch.delenv(name, raising=False)
        azure_dir = tmp_path / ".azure"
        azure_dir.mkdir()
        (azure_dir / "azureProfile.json").write_text("{not json", encoding="utf-8")

        creds = harvest_azure_credentials(azure_dir=azure_dir, include_imds=False)

        assert creds == []


# --------------------------------------------------------------------------- #
# Source 3: msal_token_cache.json                                             #
# --------------------------------------------------------------------------- #

class TestHarvestMsalCache:
    def test_parses_access_and_refresh_tokens(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        for name in ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_STORAGE_CONNECTION_STRING"):
            monkeypatch.delenv(name, raising=False)
        azure_dir = tmp_path / ".azure"
        azure_dir.mkdir()
        cache = {
            "AccessToken": {
                "u-1": {
                    "client_id": "app-guid",
                    "realm": "tenant-guid",
                    "secret": "eyJraWQ.access-token",
                }
            },
            "RefreshToken": {
                "r-1": {
                    "client_id": "app-guid",
                    "secret": "OAQABAAA.refresh-token",
                }
            },
        }
        (azure_dir / "msal_token_cache.json").write_text(json.dumps(cache), encoding="utf-8")

        creds = harvest_azure_credentials(azure_dir=azure_dir, include_imds=False)

        access = [c for c in creds if c.type == "msal_access_token"]
        refresh = [c for c in creds if c.type == "msal_refresh_token"]
        assert len(access) == 1
        assert len(refresh) == 1
        assert access[0].access_token_hash == _sha256("eyJraWQ.access-token")
        assert refresh[0].refresh_token_hash == _sha256("OAQABAAA.refresh-token")
        payload = json.dumps([c.to_dict() for c in creds])
        assert "eyJraWQ.access-token" not in payload
        assert "OAQABAAA.refresh-token" not in payload

    def test_encrypted_cache_hashes_whole_blob(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        for name in ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_STORAGE_CONNECTION_STRING"):
            monkeypatch.delenv(name, raising=False)
        azure_dir = tmp_path / ".azure"
        azure_dir.mkdir()
        blob = b"\x01\x00DPAPI-encrypted-blob"
        (azure_dir / "msal_token_cache.json").write_bytes(blob)

        creds = harvest_azure_credentials(azure_dir=azure_dir, include_imds=False)

        encrypted = [c for c in creds if c.type == "msal_encrypted_cache"]
        assert len(encrypted) == 1
        assert encrypted[0].access_token_hash == _sha256(blob)
        assert encrypted[0].extra.get("cache_size_bytes") == str(len(blob))


# --------------------------------------------------------------------------- #
# Source 4: service_principal_entries.json                                    #
# --------------------------------------------------------------------------- #

class TestHarvestServicePrincipals:
    def test_hashes_client_secret_and_certificate(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        for name in ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_STORAGE_CONNECTION_STRING"):
            monkeypatch.delenv(name, raising=False)
        azure_dir = tmp_path / ".azure"
        azure_dir.mkdir()
        entries = [
            {
                "client": "sp-guid-1",
                "tenant": "tenant-guid-1",
                "clientSecret": "sp-secret-value",
            },
            {
                "clientId": "sp-guid-2",
                "tenantId": "tenant-guid-2",
                "certificate": "AA:BB:CC:DD:EE:FF",
            },
        ]
        (azure_dir / "service_principal_entries.json").write_text(json.dumps(entries), encoding="utf-8")

        creds = harvest_azure_credentials(azure_dir=azure_dir, include_imds=False)

        sps = [c for c in creds if c.type == "service_principal"]
        assert len(sps) == 2
        secret_row = next(c for c in sps if c.client_id == "sp-guid-1")
        assert secret_row.secret_hash == _sha256("sp-secret-value")
        cert_row = next(c for c in sps if c.client_id == "sp-guid-2")
        assert cert_row.extra.get("certificate_thumbprint_hash") == _sha256("AA:BB:CC:DD:EE:FF")
        payload = json.dumps([c.to_dict() for c in sps])
        assert "sp-secret-value" not in payload
        assert "AA:BB:CC:DD:EE:FF" not in payload


# --------------------------------------------------------------------------- #
# Source 5: IMDS                                                              #
# --------------------------------------------------------------------------- #

class _FakeResponse:
    def __init__(self, body: bytes) -> None:
        self._body = body

    def read(self) -> bytes:
        return self._body

    def __enter__(self) -> "_FakeResponse":
        return self

    def __exit__(self, *exc: object) -> None:  # noqa: D401
        pass


class TestHarvestImds:
    def test_hashes_managed_identity_token(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        for name in ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_STORAGE_CONNECTION_STRING"):
            monkeypatch.delenv(name, raising=False)
        body = json.dumps(
            {
                "access_token": "eyJ0eXAiOi.mi-token",
                "client_id": "mi-client-guid",
                "resource": "https://management.azure.com/",
                "expires_in": "3600",
                "token_type": "Bearer",
            }
        ).encode("utf-8")
        with patch(
            "forge.collection.cloud.azure_credentials.urlrequest.urlopen",
            return_value=_FakeResponse(body),
        ):
            creds = harvest_azure_credentials(azure_dir=tmp_path / "empty", include_imds=True)

        mi = [c for c in creds if c.type == "managed_identity_token"]
        assert len(mi) == 1
        assert mi[0].client_id == "mi-client-guid"
        assert mi[0].access_token_hash == _sha256("eyJ0eXAiOi.mi-token")
        assert mi[0].extra.get("resource") == "https://management.azure.com/"
        assert "eyJ0eXAiOi.mi-token" not in json.dumps(mi[0].to_dict())

    def test_imds_timeout_returns_empty(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        for name in ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_STORAGE_CONNECTION_STRING"):
            monkeypatch.delenv(name, raising=False)

        def _raise(*args: object, **kwargs: object) -> None:
            raise TimeoutError("imds timeout")

        with patch(
            "forge.collection.cloud.azure_credentials.urlrequest.urlopen",
            side_effect=_raise,
        ):
            creds = harvest_azure_credentials(
                azure_dir=tmp_path / "empty", include_imds=True, imds_timeout=0.01
            )

        assert [c for c in creds if c.type == "managed_identity_token"] == []

    def test_include_imds_false_skips_probe(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        for name in ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_STORAGE_CONNECTION_STRING"):
            monkeypatch.delenv(name, raising=False)

        with patch(
            "forge.collection.cloud.azure_credentials.urlrequest.urlopen",
            side_effect=AssertionError("must not probe IMDS when disabled"),
        ):
            creds = harvest_azure_credentials(azure_dir=tmp_path / "empty", include_imds=False)

        assert creds == []


# --------------------------------------------------------------------------- #
# AzureCredential dataclass                                                   #
# --------------------------------------------------------------------------- #

class TestAzureCredentialDataclass:
    def test_default_extra_isolated(self) -> None:
        c1 = AzureCredential(type="service_principal", source="env")
        c2 = AzureCredential(type="service_principal", source="env")
        c1.extra["k"] = "v"
        assert c2.extra == {}
