#![allow(clippy::useless_conversion)] // Generated by PyO3 0.22 method wrappers.

//! Credential extraction - obfuscated implementation
//!
//! Handles credential extraction from LSASS, SAM, and memory

use pyo3::exceptions::{PyNotImplementedError, PyRuntimeError, PyValueError};
use pyo3::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

const MAX_ROE_ID_BYTES: usize = 256;
const MAX_SCOPE_ENTRIES: usize = 10_000;
const MAX_HOST_BYTES: usize = 253;
const MAX_PATH_BYTES: usize = 4096;
const MAX_DCC_BYTES: usize = 1024 * 1024;

#[pyclass]
pub struct CredentialExtractor {
    roe_id: String,
    scope_hosts: Vec<String>,
    allow_lsass: bool,
    allow_sam: bool,
}

#[pymethods]
impl CredentialExtractor {
    #[new]
    #[pyo3(signature = (roe_id, scope_hosts=None, allow_lsass=false, allow_sam=false))]
    pub fn new(
        roe_id: String,
        scope_hosts: Option<Vec<String>>,
        allow_lsass: bool,
        allow_sam: bool,
    ) -> PyResult<Self> {
        if roe_id.trim().is_empty() || roe_id.len() > MAX_ROE_ID_BYTES {
            return Err(PyErr::new::<PyValueError, _>(
                "ROE ID must contain between 1 and 256 bytes",
            ));
        }
        let scope_hosts = scope_hosts.unwrap_or_default();
        if scope_hosts.len() > MAX_SCOPE_ENTRIES
            || scope_hosts
                .iter()
                .any(|host| host.trim().is_empty() || host.len() > MAX_HOST_BYTES)
        {
            return Err(PyErr::new::<PyValueError, _>(
                "Scope hosts must contain at most 10000 non-empty hostnames of 253 bytes each",
            ));
        }

        Ok(Self {
            roe_id,
            scope_hosts,
            allow_lsass,
            allow_sam,
        })
    }

    /// Extract credentials from LSASS (Windows-only, requires allow_lsass)
    #[cfg(windows)]
    #[pyo3(signature = (target=None))]
    fn extract_from_lsass(&self, target: Option<&str>) -> PyResult<Vec<HashMap<String, String>>> {
        if !self.allow_lsass {
            return Err(PyErr::new::<PyRuntimeError, _>(
                "LSASS extraction not permitted",
            ));
        }
        self.require_scoped_target(target)?;

        // Obfuscated LSASS extraction
        // Actual implementation would use:
        // 1. DuplicateTokenEx with SE_DEBUG_PRIVILEGE
        // 2. OpenProcess to get LSASS handle
        // 3. MiniDumpWriteDump or in-memory parsing
        // All strings obfuscated using obfuscation module

        Err(PyErr::new::<PyNotImplementedError, _>(
            "LSASS extraction is not implemented in forge_core",
        ))
    }

    #[cfg(not(windows))]
    #[pyo3(signature = (target=None))]
    fn extract_from_lsass(&self, target: Option<&str>) -> PyResult<Vec<HashMap<String, String>>> {
        if !self.allow_lsass {
            return Err(PyErr::new::<PyRuntimeError, _>(
                "LSASS extraction not permitted",
            ));
        }
        self.require_scoped_target(target)?;
        Err(PyErr::new::<PyNotImplementedError, _>(
            "LSASS extraction is unsupported on this platform",
        ))
    }

    /// Extract from SAM database (Windows-only)
    #[cfg(windows)]
    #[pyo3(signature = (hive_path, target=None))]
    fn extract_from_sam(
        &self,
        hive_path: &str,
        target: Option<&str>,
    ) -> PyResult<Vec<HashMap<String, String>>> {
        if !self.allow_sam {
            return Err(PyErr::new::<PyRuntimeError, _>(
                "SAM extraction not permitted",
            ));
        }
        self.require_scoped_target(target)?;
        if hive_path.is_empty() || hive_path.len() > MAX_PATH_BYTES {
            return Err(PyErr::new::<PyValueError, _>(
                "SAM hive path must contain between 1 and 4096 bytes",
            ));
        }

        // Obfuscated SAM extraction
        // Uses obfuscated syscalls for registry access

        Err(PyErr::new::<PyNotImplementedError, _>(
            "SAM extraction is not implemented in forge_core",
        ))
    }

    #[cfg(not(windows))]
    #[pyo3(signature = (hive_path, target=None))]
    fn extract_from_sam(
        &self,
        hive_path: &str,
        target: Option<&str>,
    ) -> PyResult<Vec<HashMap<String, String>>> {
        if !self.allow_sam {
            return Err(PyErr::new::<PyRuntimeError, _>(
                "SAM extraction not permitted",
            ));
        }
        self.require_scoped_target(target)?;
        if hive_path.is_empty() || hive_path.len() > MAX_PATH_BYTES {
            return Err(PyErr::new::<PyValueError, _>(
                "SAM hive path must contain between 1 and 4096 bytes",
            ));
        }
        Err(PyErr::new::<PyNotImplementedError, _>(
            "SAM extraction is unsupported on this platform",
        ))
    }

    /// Parse DCC (Domain Cached Credentials)
    fn parse_dcc(&self, hash: &[u8]) -> PyResult<HashMap<String, String>> {
        let _ = &self.roe_id;
        if hash.is_empty() || hash.len() > MAX_DCC_BYTES {
            return Err(PyErr::new::<PyValueError, _>(
                "DCC input must contain between 1 byte and 1 MiB",
            ));
        }

        Err(PyErr::new::<PyNotImplementedError, _>(
            "DCC parsing is not implemented in forge_core",
        ))
    }

    fn is_in_scope(&self, host: &str) -> bool {
        self.scope_hosts
            .iter()
            .any(|h| host.eq_ignore_ascii_case(h))
    }
}

impl CredentialExtractor {
    fn require_scoped_target(&self, target: Option<&str>) -> PyResult<()> {
        let target = target.ok_or_else(|| {
            PyErr::new::<PyValueError, _>("An explicit scoped target is required")
        })?;
        if target.trim().is_empty() || target.len() > MAX_HOST_BYTES || !self.is_in_scope(target) {
            return Err(PyErr::new::<PyValueError, _>("Target not in scope"));
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Credential {
    pub cred_type: String,
    pub username: String,
    pub domain: String,
    pub hash: String,
    pub source: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extractor_creation() {
        let extractor = CredentialExtractor::new(
            "ROE-TEST".to_string(),
            Some(vec!["192.168.1.1".to_string()]),
            false,
            false,
        );
        assert!(extractor.is_ok());
    }
    #[test]
    fn test_credential_extractor_requires_roe_id() {
        let result = CredentialExtractor::new("".to_string(), None, false, false);
        assert!(result.is_err(), "Empty ROE ID must be rejected");

        let result = CredentialExtractor::new("   ".to_string(), None, false, false);
        assert!(result.is_err(), "Whitespace-only ROE ID must be rejected");
    }

    #[test]
    fn test_extract_lsass_blocked_without_permission() {
        let extractor = CredentialExtractor::new(
            "ROE-TEST".to_string(),
            Some(vec!["192.168.1.1".to_string()]),
            false, // allow_lsass = false
            false,
        )
        .expect("Valid CredentialExtractor construction");
        let result = extractor.extract_from_lsass(Some("192.168.1.1"));
        assert!(
            result.is_err(),
            "LSASS extraction must be blocked when allow_lsass=false"
        );
    }

    #[test]
    fn test_permitted_placeholders_do_not_report_false_success() {
        let extractor = CredentialExtractor::new(
            "ROE-TEST".to_string(),
            Some(vec!["host.example".to_string()]),
            true,
            true,
        )
        .expect("Valid CredentialExtractor construction");
        assert!(extractor.extract_from_lsass(None).is_err());
        assert!(extractor.extract_from_lsass(Some("other.example")).is_err());
        assert!(extractor.extract_from_lsass(Some("host.example")).is_err());
        assert!(extractor.extract_from_sam("sam.hive", None).is_err());
        assert!(extractor
            .extract_from_sam("sam.hive", Some("host.example"))
            .is_err());
        assert!(extractor.parse_dcc(&[]).is_err());
        assert!(extractor.parse_dcc(&[0_u8; 16]).is_err());
    }
}
