#![allow(clippy::useless_conversion)] // Generated by PyO3 0.22 function wrappers.

//! Cryptographic utilities - obfuscated implementation

use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};
use base64::{engine::general_purpose, Engine as _};
use pyo3::exceptions::{PyRuntimeError, PyValueError};
use pyo3::prelude::*;
use rand::RngCore;

const KEY_BYTES: usize = 32;
const NONCE_BYTES: usize = 12;
const TAG_BYTES: usize = 16;
const MAX_PLAINTEXT_BYTES: usize = 64 * 1024 * 1024;
const MAX_KEY_B64_BYTES: usize = 44;
const MAX_CIPHERTEXT_BYTES: usize = NONCE_BYTES + TAG_BYTES + MAX_PLAINTEXT_BYTES;
const MAX_CIPHERTEXT_B64_BYTES: usize = MAX_CIPHERTEXT_BYTES.div_ceil(3) * 4;

fn value_error(message: impl Into<String>) -> PyErr {
    PyErr::new::<PyValueError, _>(message.into())
}

fn validate_plaintext_len(len: usize) -> PyResult<()> {
    if len > MAX_PLAINTEXT_BYTES {
        return Err(value_error("Plaintext exceeds the 64 MiB limit"));
    }
    Ok(())
}

fn validate_ciphertext_b64_len(len: usize) -> PyResult<()> {
    if len > MAX_CIPHERTEXT_B64_BYTES {
        return Err(value_error("Ciphertext exceeds the 64 MiB plaintext limit"));
    }
    Ok(())
}

fn decode_key(key_b64: &str) -> PyResult<[u8; KEY_BYTES]> {
    if key_b64.len() > MAX_KEY_B64_BYTES {
        return Err(value_error("Key must be 32 bytes"));
    }

    let mut key = [0u8; KEY_BYTES];
    let decoded_len = general_purpose::STANDARD
        .decode_slice(key_b64, &mut key)
        .map_err(|error| value_error(error.to_string()))?;
    if decoded_len != KEY_BYTES {
        return Err(value_error("Key must be 32 bytes"));
    }
    Ok(key)
}

/// Encrypt at most 64 MiB of UTF-8 plaintext with AES-256-GCM.
#[pyfunction]
pub fn aes_encrypt(plaintext: &str, key_b64: &str) -> PyResult<String> {
    validate_plaintext_len(plaintext.len())?;
    let key_bytes = decode_key(key_b64)?;

    let cipher = Aes256Gcm::new_from_slice(&key_bytes)
        .map_err(|error| PyErr::new::<PyRuntimeError, _>(error.to_string()))?;

    let mut nonce_bytes = [0u8; NONCE_BYTES];
    rand::thread_rng().fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let ciphertext = cipher
        .encrypt(nonce, plaintext.as_bytes())
        .map_err(|error| PyErr::new::<PyRuntimeError, _>(error.to_string()))?;

    // Format: nonce || ciphertext (base64)
    let mut combined = Vec::with_capacity(NONCE_BYTES + ciphertext.len());
    combined.extend_from_slice(&nonce_bytes);
    combined.extend(ciphertext);

    Ok(general_purpose::STANDARD.encode(combined))
}

/// Decrypt an AES-256-GCM envelope containing at most 64 MiB of plaintext.
#[pyfunction]
pub fn aes_decrypt(ciphertext_b64: &str, key_b64: &str) -> PyResult<String> {
    let key_bytes = decode_key(key_b64)?;
    validate_ciphertext_b64_len(ciphertext_b64.len())?;

    let combined = general_purpose::STANDARD
        .decode(ciphertext_b64)
        .map_err(|error| value_error(error.to_string()))?;

    if combined.len() < NONCE_BYTES + TAG_BYTES || combined.len() > MAX_CIPHERTEXT_BYTES {
        return Err(value_error("Invalid ciphertext length"));
    }

    let (nonce_bytes, ciphertext) = combined.split_at(NONCE_BYTES);
    let nonce = Nonce::from_slice(nonce_bytes);

    let cipher = Aes256Gcm::new_from_slice(&key_bytes)
        .map_err(|error| PyErr::new::<PyRuntimeError, _>(error.to_string()))?;

    let plaintext = cipher
        .decrypt(nonce, ciphertext)
        .map_err(|error| PyErr::new::<PyRuntimeError, _>(error.to_string()))?;

    String::from_utf8(plaintext).map_err(|error| value_error(error.to_string()))
}

#[pyfunction]
pub fn generate_key() -> String {
    let mut key = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut key);
    general_purpose::STANDARD.encode(key)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_aes_roundtrip() {
        let key = generate_key();
        let original = "test_secret";

        let encrypted = aes_encrypt(original, &key).unwrap();
        let decrypted = aes_decrypt(&encrypted, &key).unwrap();

        assert_eq!(original, decrypted);
    }

    #[test]
    fn test_malformed_base64_key() {
        let result = aes_encrypt("test", "not-valid-base64!!!");
        assert!(result.is_err());
    }

    #[test]
    fn test_malformed_base64_ciphertext() {
        let key = generate_key();
        let result = aes_decrypt("not-valid-base64!!!", &key);
        assert!(result.is_err());
    }

    #[test]
    fn test_ciphertext_shorter_than_nonce() {
        let key = generate_key();
        // Eight decoded bytes are shorter than the 12-byte nonce.
        let short_ct = general_purpose::STANDARD.encode([0u8; 8]);
        let result = aes_decrypt(&short_ct, &key);
        assert!(result.is_err());
    }

    #[test]
    fn test_ciphertext_without_authentication_tag() {
        let key = generate_key();
        let nonce_only = general_purpose::STANDARD.encode([0u8; NONCE_BYTES]);
        let result = aes_decrypt(&nonce_only, &key);
        assert!(result.is_err());
    }

    #[test]
    fn test_wrong_key_decryption() {
        let key1 = generate_key();
        let key2 = generate_key();
        let encrypted = aes_encrypt("secret", &key1).unwrap();
        let result = aes_decrypt(&encrypted, &key2);
        assert!(result.is_err());
    }

    #[test]
    fn test_tampered_ciphertext() {
        let key = generate_key();
        let encrypted = aes_encrypt("secret", &key).unwrap();
        let mut decoded = general_purpose::STANDARD.decode(&encrypted).unwrap();
        // Tamper with the ciphertext (after nonce)
        if decoded.len() > 13 {
            decoded[13] ^= 0xFF;
        }
        let tampered = general_purpose::STANDARD.encode(&decoded);
        let result = aes_decrypt(&tampered, &key);
        assert!(result.is_err());
    }

    #[test]
    fn test_empty_plaintext_roundtrip() {
        let key = generate_key();
        let encrypted = aes_encrypt("", &key).unwrap();
        let decrypted = aes_decrypt(&encrypted, &key).unwrap();
        assert_eq!("", decrypted);
    }

    #[test]
    fn test_large_plaintext_roundtrip() {
        let key = generate_key();
        // 1 MB plaintext
        let original = "x".repeat(1024 * 1024);
        let encrypted = aes_encrypt(&original, &key).unwrap();
        let decrypted = aes_decrypt(&encrypted, &key).unwrap();
        assert_eq!(original, decrypted);
    }

    #[test]
    fn test_plaintext_limit_is_checked_without_large_allocation() {
        assert!(validate_plaintext_len(MAX_PLAINTEXT_BYTES).is_ok());
        assert!(validate_plaintext_len(MAX_PLAINTEXT_BYTES + 1).is_err());
    }

    #[test]
    fn test_ciphertext_limit_is_checked_before_decode() {
        assert!(validate_ciphertext_b64_len(MAX_CIPHERTEXT_B64_BYTES).is_ok());
        assert!(validate_ciphertext_b64_len(MAX_CIPHERTEXT_B64_BYTES + 1).is_err());
    }
}
