#![allow(clippy::useless_conversion)] // Generated by PyO3 0.22 method wrappers.

//! Kerberos operations - obfuscated implementation
//!
//! Handles kirbi parsing, ticket operations, and Kerberoasting

use pyo3::exceptions::{PyNotImplementedError, PyRuntimeError, PyValueError};
use pyo3::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

const MAX_ROE_ID_BYTES: usize = 256;
const MAX_SCOPE_ENTRIES: usize = 10_000;
const MAX_DOMAIN_BYTES: usize = 253;
const MAX_PATH_BYTES: usize = 4096;
const MAX_TICKET_BYTES: usize = 64 * 1024 * 1024;

/// Obfuscated Kerberos operations
#[pyclass]
pub struct KerberosOps {
    roe_id: String,
    scope_domains: Vec<String>,
    allow_lsass: bool,
    allow_kerberoast: bool,
}

#[pymethods]
impl KerberosOps {
    #[new]
    #[pyo3(signature = (roe_id, scope_domains=None, allow_lsass=false, allow_kerberoast=false))]
    pub fn new(
        roe_id: String,
        scope_domains: Option<Vec<String>>,
        allow_lsass: bool,
        allow_kerberoast: bool,
    ) -> PyResult<Self> {
        if roe_id.trim().is_empty() || roe_id.len() > MAX_ROE_ID_BYTES {
            return Err(PyErr::new::<PyValueError, _>(
                "ROE ID must contain between 1 and 256 bytes",
            ));
        }
        let scope_domains = scope_domains.unwrap_or_default();
        if scope_domains.len() > MAX_SCOPE_ENTRIES
            || scope_domains
                .iter()
                .any(|domain| domain.trim().is_empty() || domain.len() > MAX_DOMAIN_BYTES)
        {
            return Err(PyErr::new::<PyValueError, _>(
                "Scope domains must contain at most 10000 non-empty names of 253 bytes each",
            ));
        }

        Ok(Self {
            roe_id,
            scope_domains,
            allow_lsass,
            allow_kerberoast,
        })
    }

    /// Parse kirbi file (obfuscated implementation)
    #[pyo3(signature = (filepath))]
    fn parse_kirbi(&self, filepath: &str) -> PyResult<Vec<HashMap<String, String>>> {
        let _ = (&self.roe_id, self.allow_lsass);
        if filepath.is_empty() || filepath.len() > MAX_PATH_BYTES {
            return Err(PyErr::new::<PyValueError, _>(
                "Kirbi path must contain between 1 and 4096 bytes",
            ));
        }
        Err(PyErr::new::<PyNotImplementedError, _>(
            "Kirbi parsing is not implemented in forge_core",
        ))
    }

    /// Enumerate Kerberoast candidates
    fn enumerate_kerberoast_candidates(&self, domain: &str, dc_ip: &str) -> PyResult<Vec<String>> {
        if !self.allow_kerberoast {
            return Err(PyErr::new::<PyRuntimeError, _>("Kerberoast not allowed"));
        }

        if domain.len() > MAX_DOMAIN_BYTES
            || dc_ip.trim().is_empty()
            || dc_ip.len() > MAX_DOMAIN_BYTES
        {
            return Err(PyErr::new::<PyValueError, _>(
                "Domain and domain controller names must not exceed 253 bytes",
            ));
        }
        if !self.is_in_scope(domain) {
            return Err(PyErr::new::<PyValueError, _>("Domain not in scope"));
        }

        Err(PyErr::new::<PyNotImplementedError, _>(
            "Kerberoast enumeration is not implemented in forge_core",
        ))
    }

    /// Inject ticket (Windows-only, obfuscated)
    #[cfg(windows)]
    fn inject_ticket(&self, ticket_data: &[u8]) -> PyResult<bool> {
        if !self.allow_lsass {
            return Err(PyErr::new::<PyRuntimeError, _>(
                "Ticket injection not permitted",
            ));
        }
        if ticket_data.is_empty() || ticket_data.len() > MAX_TICKET_BYTES {
            return Err(PyErr::new::<PyValueError, _>(
                "Ticket data must contain between 1 byte and 64 MiB",
            ));
        }
        Err(PyErr::new::<PyNotImplementedError, _>(
            "Ticket injection is not implemented in forge_core",
        ))
    }

    #[cfg(not(windows))]
    fn inject_ticket(&self, ticket_data: &[u8]) -> PyResult<bool> {
        if !self.allow_lsass {
            return Err(PyErr::new::<PyRuntimeError, _>(
                "Ticket injection not permitted",
            ));
        }
        if ticket_data.is_empty() || ticket_data.len() > MAX_TICKET_BYTES {
            return Err(PyErr::new::<PyValueError, _>(
                "Ticket data must contain between 1 byte and 64 MiB",
            ));
        }
        Err(PyErr::new::<PyNotImplementedError, _>(
            "Ticket injection is unsupported on this platform",
        ))
    }

    /// Check if domain is in scope
    fn is_in_scope(&self, domain: &str) -> bool {
        self.scope_domains.iter().any(|d| {
            domain.eq_ignore_ascii_case(d)
                || domain
                    .to_lowercase()
                    .ends_with(&format!(".{}", d.to_lowercase()))
        })
    }
}

/// Kerberos ticket structure
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KerberosTicket {
    pub service_principal_name: String,
    pub client_name: String,
    pub domain: String,
    pub session_key_type: String,
    pub is_kerberoastable: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_kerberos_ops_creation() {
        let ops = KerberosOps::new(
            "ROE-TEST".to_string(),
            Some(vec!["test.local".to_string()]),
            false,
            false,
        );
        assert!(ops.is_ok());
    }

    #[test]
    fn test_scope_matching() {
        let ops = KerberosOps::new(
            "ROE-TEST".to_string(),
            Some(vec!["test.local".to_string()]),
            false,
            false,
        )
        .unwrap();

        assert!(ops.is_in_scope("test.local"));
        assert!(ops.is_in_scope("sub.test.local"));
        assert!(!ops.is_in_scope("other.local"));
    }
    #[test]
    fn test_kerberos_ops_requires_roe_id() {
        let result = KerberosOps::new("".to_string(), None, false, false);
        assert!(result.is_err(), "Empty ROE ID must be rejected");

        let result = KerberosOps::new("\t".to_string(), None, false, false);
        assert!(result.is_err(), "Whitespace-only ROE ID must be rejected");
    }

    #[test]
    fn test_parse_kirbi_fails_closed_until_implemented() {
        let ops = KerberosOps::new(
            "ROE-TEST".to_string(),
            Some(vec!["test.local".to_string()]),
            false,
            false,
        )
        .expect("Valid KerberosOps construction");
        let result = ops.parse_kirbi("nonexistent.kirbi");
        assert!(
            result.is_err(),
            "Unimplemented parsing must not report success"
        );
    }

    #[test]
    fn test_kerberoast_rejects_out_of_scope_domain() {
        let ops = KerberosOps::new(
            "ROE-TEST".to_string(),
            Some(vec!["allowed.local".to_string()]),
            false,
            true,
        )
        .expect("Valid KerberosOps construction");
        let result = ops.enumerate_kerberoast_candidates("notallowed.local", "10.0.0.1");
        assert!(result.is_err(), "Out-of-scope domain must be rejected");
    }

    #[test]
    fn test_kerberoast_accepts_scoped_subdomain_before_failing_closed() {
        let ops = KerberosOps::new(
            "ROE-TEST".to_string(),
            Some(vec!["allowed.local".to_string()]),
            false,
            true,
        )
        .expect("Valid KerberosOps construction");
        let result = ops.enumerate_kerberoast_candidates("sub.allowed.local", "10.0.0.1");
        assert!(
            result.is_err(),
            "Unimplemented enumeration must fail closed"
        );
    }
}
