#![allow(clippy::useless_conversion)] // Generated by PyO3 0.22 method wrappers.

//! Pass-the-hash execution - obfuscated implementation

use pyo3::exceptions::{PyNotImplementedError, PyRuntimeError, PyValueError};
use pyo3::prelude::*;

const MAX_ROE_ID_BYTES: usize = 256;
const MAX_SCOPE_ENTRIES: usize = 10_000;
const MAX_HOST_BYTES: usize = 253;
const MAX_HASH_BYTES: usize = 4096;
const MAX_COMMAND_BYTES: usize = 64 * 1024;

#[pyclass]
pub struct PTHExecutor {
    roe_id: String,
    scope_hosts: Vec<String>,
    allow_pth: bool,
}

#[pymethods]
impl PTHExecutor {
    #[new]
    #[pyo3(signature = (roe_id, scope_hosts=None, allow_pth=false))]
    pub fn new(
        roe_id: String,
        scope_hosts: Option<Vec<String>>,
        allow_pth: bool,
    ) -> PyResult<Self> {
        if roe_id.trim().is_empty() || roe_id.len() > MAX_ROE_ID_BYTES {
            return Err(PyErr::new::<PyValueError, _>(
                "ROE ID must contain between 1 and 256 bytes",
            ));
        }
        let scope_hosts = scope_hosts.unwrap_or_default();
        if scope_hosts.len() > MAX_SCOPE_ENTRIES
            || scope_hosts
                .iter()
                .any(|host| host.trim().is_empty() || host.len() > MAX_HOST_BYTES)
        {
            return Err(PyErr::new::<PyValueError, _>(
                "Scope hosts must contain at most 10000 non-empty hostnames of 253 bytes each",
            ));
        }

        Ok(Self {
            roe_id,
            scope_hosts,
            allow_pth,
        })
    }

    /// Execute pass-the-hash
    #[pyo3(signature = (target, hash, command=None))]
    fn execute(&self, target: &str, hash: &str, command: Option<&str>) -> PyResult<String> {
        let _ = (&self.roe_id, &hash, &command);

        if !self.allow_pth {
            return Err(PyErr::new::<PyRuntimeError, _>("PTH not permitted"));
        }

        if target.trim().is_empty() || target.len() > MAX_HOST_BYTES {
            return Err(PyErr::new::<PyValueError, _>("Invalid target"));
        }
        if hash.trim().is_empty() || hash.len() > MAX_HASH_BYTES {
            return Err(PyErr::new::<PyValueError, _>("Invalid hash input"));
        }
        if command.is_some_and(|value| value.len() > MAX_COMMAND_BYTES) {
            return Err(PyErr::new::<PyValueError, _>(
                "Command exceeds the 64 KiB limit",
            ));
        }
        if !self.is_in_scope(target) {
            return Err(PyErr::new::<PyValueError, _>("Target not in scope"));
        }

        Err(PyErr::new::<PyNotImplementedError, _>(
            "PTH execution is not implemented in forge_core",
        ))
    }

    fn is_in_scope(&self, host: &str) -> bool {
        self.scope_hosts
            .iter()
            .any(|h| host.eq_ignore_ascii_case(h))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pth_creation() {
        let executor = PTHExecutor::new(
            "ROE-TEST".to_string(),
            Some(vec!["192.168.1.1".to_string()]),
            false,
        );
        assert!(executor.is_ok());
    }

    #[test]
    fn test_pth_requires_nonblank_roe_id() {
        assert!(PTHExecutor::new(" ".to_string(), None, false).is_err());
    }

    #[test]
    fn test_pth_gates_and_never_reports_placeholder_success() {
        let blocked = PTHExecutor::new(
            "ROE-TEST".to_string(),
            Some(vec!["host.example".to_string()]),
            false,
        )
        .unwrap();
        assert!(blocked.execute("host.example", "hash", None).is_err());

        let allowed = PTHExecutor::new(
            "ROE-TEST".to_string(),
            Some(vec!["host.example".to_string()]),
            true,
        )
        .unwrap();
        let result = allowed.execute("host.example", "hash", None);
        assert!(result.is_err(), "Unimplemented PTH must fail closed");
    }
}
